# Generated by Django 4.0.1 on 2022-10-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(max_length=10, null=True, verbose_name='Connection Type')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_nub', models.IntegerField(null=True, verbose_name='Consumer Num')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=40, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=20, null=True, verbose_name='Password')),
                ('mobile', models.CharField(max_length=10, null=True, verbose_name='Mobile')),
                ('Door_No', models.IntegerField(null=True, verbose_name='Door No')),
                ('pincode', models.IntegerField(null=True, verbose_name='Pincode')),
                ('address', models.TextField(max_length=50, null=True, verbose_name='Address')),
                ('ctype', models.CharField(blank=True, default='NewCustomer', max_length=100, null=True, verbose_name='CustomerType')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.connection')),
            ],
        ),
        migrations.CreateModel(
            name='Eb_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Name')),
                ('place', models.CharField(max_length=20, null=True, verbose_name='Place')),
                ('mobile', models.CharField(max_length=10, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=20, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Adddress')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True, verbose_name='Name')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
                ('mobile', models.CharField(max_length=10, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=20, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Adddress')),
            ],
        ),
        migrations.CreateModel(
            name='Unitper_Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10, null=True, verbose_name='Per Unit Amount')),
                ('connection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.connection')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_consumed', models.CharField(max_length=10, null=True, verbose_name='Unit Consumed')),
                ('start_date', models.DateField(null=True, verbose_name='Start date')),
                ('end_date', models.DateField(null=True, verbose_name='End date')),
                ('amount', models.CharField(max_length=10, null=True, verbose_name='Amount')),
                ('month', models.CharField(max_length=10, null=True, verbose_name='Month')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.customer')),
                ('per_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.unitper_amount')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.connection')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(null=True, verbose_name='pay date')),
                ('pay_time', models.TimeField(null=True, verbose_name='pay time')),
                ('email', models.EmailField(max_length=25, null=True, verbose_name='Email')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.unit')),
            ],
        ),
    ]
