# Generated by Django 4.0.1 on 2022-10-11 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_payment_pay_date_alter_payment_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='master.unit'),
            preserve_default=False,
        ),
    ]
