# Generated by Django 4.0.1 on 2022-10-11 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='master.unit'),
        ),
    ]
